Repository bpm-crafters/process-engine-worker, pull requests merged in 2024-09, with the labels that each got.

#29 introduce result resolver
  README.md
  examples/order-fulfillment/src/main/java/dev/bpmcrafters/example/order/fulfillment/inventory/adapter/in/worker/CreateInvoiceWorker.java
  examples/order-fulfillment/src/main/java/dev/bpmcrafters/example/order/fulfillment/inventory/infrastructure/InventoryConfiguration.java
  spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengine/worker/configuration/ProcessEngineWorkerAutoConfiguration.kt
  spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengine/worker/registrar/ExceptionResolver.kt
  spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengine/worker/registrar/ParameterResolver.kt
  spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengine/worker/registrar/ProcessEngineStarterRegistrar.kt
  spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengine/worker/registrar/ReflectionUtils.kt
  spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengine/worker/registrar/ResultResolver.kt
  spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengine/worker/registrar/VariableConverter.kt
  spring-boot-starter/src/test/kotlin/dev/bpmcrafters/processengine/worker/registrar/ReflectionUtilsTest.kt
  spring-boot-starter/src/test/kotlin/dev/bpmcrafters/processengine/worker/registrar/ResultResolverTest.kt
Labels: Prio: MUST, Type: enhancement

#24 Update to Camunda 8.5 #16
  examples/order-fulfillment/pom.xml
Labels: Type: bug

#32 support optional variable injection
  README.md
  spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengine/worker/Variable.kt
  spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengine/worker/registrar/ParameterResolver.kt
  spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengine/worker/registrar/ProcessEngineStarterRegistrar.kt
  spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengine/worker/registrar/ReflectionUtils.kt
  spring-boot-starter/src/test/kotlin/dev/bpmcrafters/processengine/worker/registrar/ParameterResolverTest.kt
Labels: Prio: MUST
